name: Jude
description: A home automation application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^4.0.1+1
  http: ^0.12.2
  flutter_vlc_player: ^1.0.0
  flutter_beep: ^1.0.0
  porcupine: ^1.9.13
  wifi_configuration: ^1.2.1
  #flutter_beep: ^0.3.0
  whatsapp_share: ^1.1.1
  #flutter_ffmpeg: ^0.4.0
  notifications: ^1.1.0
  video_player: ^0.10.1
  web_socket_channel: ^1.1.0
  #porcupine: ^1.9.13
  url_launcher: ^5.4.2
  #contacts_service: ^0.4.6  
  wifi: ^0.1.5
  wifi_iot: ^0.2.0
  intl: ^0.16.1
  badges: ^1.1.6
  shared_preferences: ^2.0.6
  pull_to_refresh: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  scroll_to_index: any
  speech_to_text: ^2.3.0
  lite_rolling_switch: ^0.1.1
  highlight_text: ^0.7.2
  webview_flutter: ^0.3.0
  carousel_pro: ^1.0.0
  #simply_wifi: ^1.0.5
  shake: ^0.1.0
  connectivity: any 
  weather: ^1.2.4
  flutter_tts: ^0.7.0
  flutter_barcode_scanner: ^1.0.1
  chewie: ^0.9.7
  
  web_scraper: ^0.0.3
  avatar_glow: ^1.2.0
  #cupertino_icons: ^1.0.0
  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.3.0
  english_words: ^3.1.0 
  #path_provider: ^0.4.1
  #flutter_barcode_scanner: 
  #barcode_scan: any
  #flutter_barcode_scanner: ^2.0.0  
  #qr_flutter: ^3.2.0
  barcode_widget: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3 
  flutter_launcher_name: ^0.0.1 
  
flutter_icons:
  android: true
  ios: true
  image_path: "images/hellojude.png" 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_launcher_name:
  name: "Jude Home"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/me.png
     - images/rocketJude.jpg
     - images/jude.png
     - images/ironman.png
     - images/lightbulb.jpg
     - images/lightbulb2.jpg
     - images/lightsoff.jpg
     - images/music.jpg
     - images/music-removebg-preview.png
     - images/music2.png
     - images/weather.png
     - images/hellojude.png
     - images/sun.png
     - images/weather2.jpg
     - images/pauseplay3.png
     - images/door.png
     - images/pauseplay2-removebg-preview-removebg-preview.png
     - images/lightsoff-removebg-preview (1).png
     - images/lightbulb2-removebg-preview.png
     - images/weather2-removebg-preview.png
     - images/pauseplay3.png
     - images/keja.png
     - images/livingroom01-removebg-preview.png
     - images/Organized_Bedroom-removebg-preview.png
     - images/curtainopener.png
     - images/livingroom.png
     - images/home.png
     - images/tvicon.png
     - images/notefic.png
     - images/Alamp.jpg
     - images/Alampoff.jpg
     - images/blackhouse2.jpg
     - images/cup_coffee.png
     - images/online.png
     - images/love.png
     - images/book.png
     - images/moon.png
     - images/exit.png
     - images/fridge-removebg-preview.png
     - images/groceriesImage-removebg-preview.png
     - images/sentry_mode-removebg-preview.png
     - images/settings_icon-removebg-preview.png
     - images/shopping_list-removebg-preview.png
     - images/calendar-removebg-preview.png
     - images/scan-removebg-preview (1).png
     - images/me2X.jpeg 
     - images/onlinehome-removebg-preview (1).png
     - images/judex.png
     - images/rent_key.png
     - images/Judemilkshake.jpg
     - images/judemeat.png
     - images/judegroceries.png
     - images/judebakes.jpg
     - images/sentryXleo.png
     - images/judedrinks.png
     - images/judecake.jpg
     - images/judeicecream.jpg
     - images/grolist.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
